src/classroom/urls.py
from django.urls import path 
from . import views

app_name = 'classroom'

urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create_classroom, name = 'create_classroom'),
    path('join/', views.join_classroom, name = 'join_classroom'),
    path('open/<int:pk>/', views.open_classroom, name = 'open_classroom'),
    path('<int:pk>', views.delete_classroom, name = 'delete_classroom'),
    path('<int:pk>/members', views.members, name = 'members_classroom'),
    path('assignment/<int:pk>/student_work', views.student_work, name = 'student_work'),
    path('assignment/create', views.assignment_create, name = 'assignment_create'),
    path('assignment/<int:pk>', views.assignment_submit, name = 'assignment_submit'),
    path('assignment/<int:pk>/turnin/', views.turnin, name = 'turnin'),
    path('assignment/<int:pk>/unsubmit/', views.unsubmit, name = 'unsubmit'),
    path('assignment/<int:pk>/unsubmit_file/', views.unsubmit_file, name = 'unsubmit_file'),
    path('todo/', views.todo, name = 'todo'),
    path('toreview/', views.toreview, name = 'toreview'),
    path('<int:pk>/classwork/', views.classwork, name = 'classwork'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views


from . import views


urlpatterns = [
    path('comments', include('comments.urls')),
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls')),
    path('', views.landing, name='landing-page'),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('posts/', include('posts.urls')),
    path('whiteboard/', include('whiteboard.urls')),
    path('assignments/', include('assignments.urls')),
    path('ide/', include('ide.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('contactus/', include('contactus.urls')),
    path('password-reset/', 
    auth_views.PasswordResetView.as_view(
        template_name = 'users/password_reset.html'),
        name = 'password_reset'
    ),
    path('password-reset/done/', 
    auth_views.PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'),
        name = 'password_reset_done'
    ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
    ),
        name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
    ),
      name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/courses/urls.py
from django.urls import path 
from . import views

app_name = 'courses'

urlpatterns = [
    path('course-list', views.course_list, name='course_list'),
    path('create-course', views.create_course, name='create_course'),
    path('update-course/<int:pk>', views.update_course, name='update_course'),
    path('delete-course/<int:pk>', views.delete_course, name='delete_course'),
]

src/ide/urls.py
from django.urls import path 
from . import views

app_name = 'ide'

urlpatterns = [
    path('', views.ide, name="ide"),
    path('problems/', views.problems, name="problems"),
]

src/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings

from . import views

app_name= 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="users/login.html"),name="login"),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL},name="logout"),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

src/whiteboard/urls.py
from django.urls import path 
from . import views

app_name = 'whiteboard'

urlpatterns = [
    path('', views.whiteboard, name='whiteboard'),
    path('live/', views.live, name='live'),
]

src/core/views.py
from django.shortcuts import render
from newsletter.forms import SubscribeForm
from contactus.forms import ContactUsForm

def landing(request):
    subscribe_form = SubscribeForm()
    contactus_form = ContactUsForm()
    context = {
        'title': "Home",
        'subscribe_form':subscribe_form,
        'contactus_form':contactus_form
        }
    return render(request, "landing_page.html", context)

src/core/templates/partials/_alerts.html
{% if messages %}
  {% for message in messages %}
    <div id="message" class="container">
      <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <strong>
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error: 
          {% else %}
            {{ message.tags|title }}
          {% endif %}
        </strong>
        {{ message }}
      </div>
    </div>
  {% endfor %}
{% endif %}

src/core/templates/partials/_footer.html
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
        <span>Copyright &copy; Your Website 2020</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

src/core/templates/partials/_head.html
{% load static %}


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
  
    
  
    <!-- Custom fonts for this template-->
    <link href="{% static 'mainapp/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  
    <!-- Custom styles for this template-->
    <link href="{% static 'mainapp/css/sb-admin-2.min.css' %}" rel="stylesheet">
    
    <!-- Custom Styles -->
    <link rel="stylesheet" href="{% static 'mainapp/css/styles.css' %}">


     <!-- Bootstrap core JavaScript-->
    <script src="{% static 'mainapp/vendor/jquery/jquery.min.js' %}" defer></script>
    <script src="{% static 'mainapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}" defer></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'mainapp/vendor/jquery-easing/jquery.easing.min.js' %}" defer></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'mainapp/js/sb-admin-2.min.js' %}" defer></script>

    <script src="{% static 'mainapp/js/script.js' %}" defer></script>

    {% if 'todo' in request.path %}
        <script src="{% static 'mainapp/js/todo.js' %}" defer></script>
    {% endif %}

src/core/templates/partials/_logout_modal.html
  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'users:logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

src/core/templates/partials/_sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'classroom:home' %}">
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-book-open"></i>
      </div>
      <div class="sidebar-brand-text mx-3"> L.C.R </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:home' %}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Classrooms</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Options
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'classroom:home' %}">
        <i class="fas fa-fw fa-cog"></i>
        <span>Classrooms</span>
      </a>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:todo' %}" >
        <i class="fas fa-fw fa-wrench"></i>
        <span>To Do</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:toreview' %}" >
        <i class="fas fa-fw fa-wrench"></i>
        <span>To Review</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:assignment_create' %}">
        <i class="fas fa-fw fa-chart-area"></i>
        <span>Create Assignment</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Features
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    {% if 'open' in request.path %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'classroom:classwork' classroom.pk %}" >
          <i class="fas fa-fw fa-folder"></i>
          <span>Classworks</span>
        </a>
      </li>
    {% endif %}

    <!-- Nav Item - Charts -->
    



    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'whiteboard:whiteboard' %}">
        <i class="fas fa-fw fa-table"></i>
        <span>Whiteboard</span></a>
    </li>
    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'whiteboard:live' %}">
        <i class="fas fa-fw fa-table"></i>
        <span>Liveboard</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'courses:course_list' %}">
        <i class="fas fa-fw fa-table"></i>
        <span>Courses</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'ide:ide' %}">
        <i class="fas fa-fw fa-table"></i>
        <span>IDE</span></a>
    </li>

     <!-- Nav Item - Tables -->
     <li class="nav-item">
      <a class="nav-link" href="{% url 'ide:problems' %}">
        <i class="fas fa-fw fa-table"></i>
        <span>Problem Statements</span></a>
    </li>
     <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="https://www.quizizz.com/" target="_blank" rel="noopener noreferrer">
        <i class="fas fa-fw fa-table"></i>
        <span>Quiz</span></a>
    </li>
     <!-- Nav Item - Tables -->
   
    <!-- Nav Item - Tables -->
    
    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="https://www.google.com/calendar/about/" target="_blank" rel="noopener noreferrer">
        <i class="fas fa-fw fa-table"></i>
        <span>Google Calender</span></a>
    </li>
    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="https://evernote.com/" target="_blank" rel="noopener noreferrer">
        <i class="fas fa-fw fa-table"></i>
        <span>Evernote</span></a>
    </li>
     <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="https://www.howstuffworks.com/" target="_blank" rel="noopener noreferrer">
        <i class="fas fa-fw fa-table"></i>
        <span>How stuff works</span></a>
    </li>
     <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="https://www.wolframalpha.com/" target="_blank" rel="noopener noreferrer">
        <i class="fas fa-fw fa-table"></i>
        <span>Wolfram Alpha</span></a>
    </li>
     <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="https://www.mentimeter.com/" target="_blank" rel="noopener noreferrer">
        <i class="fas fa-fw fa-table"></i>
        <span>Mentimeter</span></a>
    </li>
     <!-- Nav Item - Tables -->
    
      <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="https://kids.nationalgeographic.com/" target="_blank" rel="noopener noreferrer">
        <i class="fas fa-fw fa-table"></i>
        <span>National Geography Kids</span></a>
    </li>
    
    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="https://trello.com/" target="_blank" rel="noopener noreferrer">
        <i class="fas fa-fw fa-table"></i>
        <span>Kanban Board</span></a>
    </li>
    
    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="https://www.kialo.com/" target="_blank" rel="noopener noreferrer">
        <i class="fas fa-fw fa-table"></i>
        <span>Now Comment</span></a>
    </li>
    
     <!-- Nav Item - Tables -->
    
    
     <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="https://edpuzzle.com/" target="_blank" rel="noopener noreferrer">
        <i class="fas fa-fw fa-table"></i>
        <span>Edpuzzle</span></a>
    </li>
     <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="https://note.ly/" target="_blank" rel="noopener noreferrer">
        <i class="fas fa-fw fa-table"></i>
        <span>Sticky notes</span></a>
    </li>
    <li class="nav-item">
    <a class="nav-link" href="https://elevateapp.com/" target="_blank" rel="noopener noreferrer">
      <i class="fas fa-fw fa-table"></i>
      <span>Elevate</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="http://www.wordupapp.co/" target="_blank" rel="noopener noreferrer">
      <i class="fas fa-fw fa-table"></i>
      <span>Wordup</span></a>
  </li>
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

  </ul>

  <!-- End of Sidebar -->

src/core/templates/partials/_topbar.html
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
      <div class="input-group">
        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search fa-sm"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

      <!-- Nav Item - Search Dropdown (Visible Only XS) -->
      <li class="nav-item dropdown no-arrow d-sm-none">
        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-search fa-fw"></i>
        </a>
        <!-- Dropdown - Messages -->
        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
          <form class="form-inline mr-auto w-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      {% if request.path == '/classroom/' %}
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="text-dark font-weight-bold">&#43;</span>
          </a>
          <!-- Dropdown - User Information -->
          <!-- Button trigger modal -->
          <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
            <a class="dropdown-item" data-toggle="modal" data-target="#exampleModalCenter" href="#">
              Create Classroom
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" data-toggle="modal" data-target="#exampleModal" href="#">
              Join Classroom
            </a>
          </div>
        
        </li>
      {% endif %}

      <!-- Nav Item - Alerts -->
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <!-- Counter - Alerts -->
          <span class="badge badge-danger badge-counter">3+</span>
        </a>
        <!-- Dropdown - Alerts -->
        <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
          <h6 class="dropdown-header">
            Alerts Center
          </h6>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="mr-3">
              <div class="icon-circle bg-primary">
                <i class="fas fa-file-alt text-white"></i>
              </div>
            </div>
            <div>
              <div class="small text-gray-500">December 12, 2019</div>
              <span class="font-weight-bold">A new monthly report is ready to download!</span>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="mr-3">
              <div class="icon-circle bg-success">
                <i class="fas fa-donate text-white"></i>
              </div>
            </div>
            <div>
              <div class="small text-gray-500">December 7, 2019</div>
              $290.29 has been deposited into your account!
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="mr-3">
              <div class="icon-circle bg-warning">
                <i class="fas fa-exclamation-triangle text-white"></i>
              </div>
            </div>
            <div>
              <div class="small text-gray-500">December 2, 2019</div>
              Spending Alert: We've noticed unusually high spending for your account.
            </div>
          </a>
          <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
        </div>
      </li>

      <!-- Nav Item - Messages -->
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <!-- Counter - Messages -->
          <span class="badge badge-danger badge-counter">7</span>
        </a>
        <!-- Dropdown - Messages -->
        <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
          <h6 class="dropdown-header">
            Message Center
          </h6>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
              <div class="status-indicator bg-success"></div>
            </div>
            <div class="font-weight-bold">
              <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
              <div class="small text-gray-500">Emily Fowler · 58m</div>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
              <div class="status-indicator"></div>
            </div>
            <div>
              <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
              <div class="small text-gray-500">Jae Chun · 1d</div>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
              <div class="status-indicator bg-warning"></div>
            </div>
            <div>
              <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
              <div class="small text-gray-500">Morgan Alvarez · 2d</div>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
              <div class="status-indicator bg-success"></div>
            </div>
            <div>
              <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
              <div class="small text-gray-500">Chicken the Dog · 2w</div>
            </div>
          </a>
          <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
        </div>
      </li>

      <div class="topbar-divider d-none d-sm-block"></div>

      <!-- Nav Item - User Information -->
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.username }}</span>
          <img class="img-profile rounded-circle" src="{{ request.user.profile.image.url }}">
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="{% url 'users:profile' %}">
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            Profile
          </a>
          <a class="dropdown-item" href="#">
            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
            Settings
          </a>
          <a class="dropdown-item" href="#">
            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
            Activity Log
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Logout
          </a>
        </div>
      </li>

    </ul>

  </nav>
  <!-- End of Topbar -->