src/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views


from . import views


urlpatterns = [
    path('comments', include('comments.urls')),
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls')),
    path('', views.landing, name='landing-page'),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('posts/', include('posts.urls')),
    path('whiteboard/', include('whiteboard.urls')),
    path('assignments/', include('assignments.urls')),
    path('ide/', include('ide.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('contactus/', include('contactus.urls')),
    path('password-reset/', 
    auth_views.PasswordResetView.as_view(
        template_name = 'users/password_reset.html'),
        name = 'password_reset'
    ),
    path('password-reset/done/', 
    auth_views.PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'),
        name = 'password_reset_done'
    ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
    ),
        name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
    ),
      name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/courses/urls.py
from django.urls import path 
from . import views

app_name = 'courses'

urlpatterns = [
    path('course-list', views.course_list, name='course_list'),
    path('create-course', views.create_course, name='create_course'),
    path('update-course/<int:pk>', views.update_course, name='update_course'),
    path('delete-course/<int:pk>', views.delete_course, name='delete_course'),
]

src/ide/urls.py
from django.urls import path 
from . import views

app_name = 'ide'

urlpatterns = [
    path('', views.ide, name="ide"),
    path('problems/', views.problems, name="problems"),
]

src/courses/models.py
from django.contrib.auth.models import User
from PIL import Image
from django.db import models


class Course(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    link = models.URLField(max_length=500)
    image = models.ImageField(default = 'courses/default.jpg', upload_to='courses/')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super().save(force_insert, force_update, using, update_fields)

        img = Image.open(self.image.path)
        
        if img.height > 400 or img.width > 400:
            output_size = (400,400)
            img.thumbnail(output_size)
            img.save(self.image.path)


class FavouriteCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

src/courses/forms.py
from django import forms
from .models import Course


class CourseCreationForm(forms.Form):
    title = forms.CharField(max_length=200)
    description = forms.CharField(widget=forms.Textarea)
    link = forms.URLField(help_text='Enter the YT link')
    image = forms.ImageField(allow_empty_file=True)

class CourseUpdateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['title', 'description', 'link', 'image']

src/courses/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Course, FavouriteCourse
from .forms import CourseCreationForm, CourseUpdateForm


def course_list(request):
    context = {
        'courses': Course.objects.all(),
    }
    return render(request, 'courses/course_list.html', context)

@login_required
def create_course(request):
    if request.method == 'POST':
        form = CourseCreationForm(request.POST, request.FILES)
        if form.is_valid():
            course = Course(
                title=form.cleaned_data.get('title'),
                description=form.cleaned_data.get('description'),
                link=form.cleaned_data.get('link'),
                image=form.cleaned_data.get('image'),
                created_by = request.user
            )
            course.save()
            return redirect('courses:course_list')
    else:
        form = CourseCreationForm()
    context={'form': form}
    return render(request, 'courses/create_course.html', context)

@login_required
def update_course(request, pk):
    course = get_object_or_404(Course, pk=pk)
    if request.method=='POST':
        form = CourseUpdateForm(request.POST,request.FILES,instance=course)
        if form.is_valid():
            form.save()
            messages.success(request, 'Course Updated Successfully')
        else:
            messages.danger(request, 'Course Updated Failed')

        return redirect('courses:update_course', course.pk)
    else:
        form = CourseUpdateForm(instance=course)
    context = {'form': form, 'course':course}
    return render(request, 'courses/course_update.html', context)

@login_required
def delete_course(request, pk):
    if request.method=='POST':
        course = get_object_or_404(Course, pk=pk)
        course.delete()
        messages.success(request, 'Course Deleted Successfully !')
        return redirect('courses:course_list')

src/courses/templates/courses/course_list.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %} Courses {% endblock title %}

{% block content %}
<div class="d-flex justify-content-end">
    <a href = "{% url 'courses:create_course' %}" class="btn btn-outline-dark"><img src = "{% static 'mainapp/icons/add.svg' %}" > Add a new course</a>
</div>

<div class="row">
    <!-- CARD -->
    {% for course in courses %}
        <div class="col-3">
            <div class="card shadow">
                <img class="card-img-top img-fluid" src="{{ course.image.url }}" alt="">
                <div class="card-body">
                    <h5 class="card-title text-dark font-weight-bold"><strong>{{ course.title }}</strong></h5>
                    <p class="card-text">{{ course.description }}</p>
                    <div class="d-flex flex-row">
                        <a class="mr-auto btn btn-circle" href=""><img src="{% static 'mainapp/icons/star.svg' %}" alt=""></a>
                        <a class="btn" href="{{ course.link }}" target="_blank">Go to the course</a>
                    </div>
                    {% if course.created_by == request.user %}
                        <a class="btn btn-sm btn-danger float-right mt-1" href="{% url 'courses:update_course' course.pk %}" target="_blank">Update course</a>
                    {% endif %}
                </div>
            </div>
        </div>

    <!-- END CARD -->
    {% endfor %}
</div>
{% endblock content %}

src/courses/templates/courses/course_update.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block title %} Course | Update {% endblock title %}

{% block content %}

<div class="row">
    <div class="col-lg-8 mx-auto">
        <div class="d-flex justify-content-center">
            <img src="{{ course.image.url }}" class="img-fluid" alt="...">
        </div>
        <div class="p-3">
            <form class="user" method='POST' enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form | crispy }}
                <button type='submit' class="btn btn-sm btn-primary float-left mb-3">Update Course</button>
            </form>
            <form action="{% url 'courses:delete_course' course.pk %}" method="POST">
                {% csrf_token %}
                <button type='submit' class="btn btn-sm btn-danger float-right mb-3">Delete Course</button>
            </form>
        </div>

    </div>
</div>

        

{% endblock content %}

src/courses/templates/courses/create_course.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block title %} Create Course {% endblock title %}

{% block content %}


<!-- Nested Row within Card Body -->
<div class="row">
    <div class="col-lg-7 mx-auto">
        <div class="p-5">
            <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Add a New Course !</h1>
            </div>
            <hr>
            <form class="user" method='POST' enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form | crispy }}
                <button type='submit' class="btn btn-small btn-primary btn-user btn-block">Add Course</button>
            </form>
        </div>
    </div>
</div>


{% endblock content %}